# This is TOML document.

name = "esearch"
port = 18092

[log]
    file_path   = "/Users/qulei/mywork/service-esearch/logs/logs.log"
    max_size    = 1024                    # 1G
    max_backups = 2                       # 2 copy
    max_age     = 20                      # 20 days
    level       = "info"
    compress    = false

[discover]
    endpoints = ["127.0.0.1:8500"]
    [discover.register]
        ttl      = 10000                  # 10s
        interval = 10000                  # 10s
    [discover.resolver]
        services = []

[elastic]
    hosts = ["http://172.31.40.234:9200"]
    auth  = ""
