name = "esearch"
port = 18092

[logger]
  file_path = "/Users/qulei/mywork/service-esearch/logs/logs.log"
  max_size = 1024   # 1G
  max_backups = 2   # 2 copy
  max_age = 20      # 20 days
  level = 0         # INFO
  compress = false

[discovery]
  endpoints = ["127.0.0.1:8500"]

[elastic]
  hosts = ["http://172.31.40.234:9200"]
  auth = ""
